name: voici-dev
channels:
  - conda-forge
dependencies:
  - pip
  - black
  - pytest
  - yarn=3
  - nodejs=18
  - pip:
    - ruff==0.0.258
    - voila>=0.5.5
    - voila-material>=0.4.3
    - jupyterlite-core[lab]>=0.2.0,<0.3.0
    - jupyterlite-xeus-python >= 1.0.0a3
